import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Trust from "../components/Trust/Trust";
import Video from "../components/Video";
import Better from "../components/Better";
import Ways from "../components/Ways";
import Create from "../components/Create";
import Feature from "../components/Feature";
import Knowledge from "../components/Knowledge";
import Stamps from "../components/Stamps";
import Resources from "../components/Resources";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Opus</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Layout>
                    <Hero />
                    <Trust />
                    <Video />
                    <Better />
					<Ways/>
					<Create/>
					<Feature/>
					<Knowledge/>
					<Stamps/>
					<Resources/>
					<Footer/>
                </Layout>
            </main>
        </>
    );
}
