import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Whenever from "../components/Whenever";
import Sharing from "../components/Sharing";
import Group from "../components/Group";
import Hot from "../components/Hot";
import Publish from "../components/Publish";
import Pricing from "../components/Pricing";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>TechSolv</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Layout>
					<Hero/>
					<Whenever/>
					<Sharing/>
					<Group/>
					<Hot/>
					<Publish/>
					<Pricing/>
					<Footer/>
				</Layout>
            </main>
        </>
    );
}
